### ISSUE TITLE
Misleading error message for invalid parameter in PARAM_ORDER

### ISSUE THREAD

**Issue by szhorvat** [igraph/stimulus#5]
When including a non-existent parameter in `PARAM_ORDER` (in R), the error message claims that the parameter appears twice:

```
RuntimeError: parameter 'foo' appears twice in PARAM_ORDER for function 'igraph_get_k_shortest_paths'
```

Tested with 0.21.0

**Comment by ntamas** [comment]
Fixed in https://github.com/igraph/stimulus/commit/b49982ffa657db51e1636abc4e26f10495faec65
